#include <kd/dis/dis386.h>

i386_instruction_t opcode_table_1[256] = {
    // 0x00
    {"ADD",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"ADD",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"ADD",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"ADD",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"ADD",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"ADD",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"PUSH ES", 0,          0,              0,              0},
    {"POP ES",  0,          0,              0,              0},
    {"OR",      MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"OR",      MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"OR",      MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"OR",      MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"OR",      0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"OR",      0,          PARAM_EAX,      PARAM_IMM,      0},
    {"PUSH CS", 0,          0,              0,              0},
    {"",        TWO_BYTE,   0,              0,              0},

    // 0x10
    {"ADC",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"ADC",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"ADC",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"ADC",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"ADC",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"ADC",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"PUSH SS", 0,          0,              0,              0},
    {"POP SS",  0,          0,              0,              0},
    {"SBB",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"SBB",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"SBB",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"SBB",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"SBB",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"SBB",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"PUSH DS", 0,          0,              0,              0},
    {"POP DS",  0,          0,              0,              0},

    // 0x20
    {"AND",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"AND",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"AND",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"AND",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"AND",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"AND",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"",        SEG_ES,     0,              0,              0},
    {"DAA",     0,          0,              0,              0},
    {"SUB",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"SUB",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"SUB",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"SUB",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"SUB",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"SUB",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"",        SEG_CS,     0,              0,              0},
    {"DAS",     0,          0,              0,              0},

    // 0x30
    {"XOR",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"XOR",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"XOR",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"XOR",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"XOR",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"XOR",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"",        SEG_SS,     0,              0,              0},
    {"AAA",     0,          0,              0,              0},
    {"CMP",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"CMP",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"CMP",     MODRM,      PARAM_REG8,     PARAM_RM8 ,     0},
    {"CMP",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"CMP",     0,          PARAM_AL,       PARAM_UI8 ,     0},
    {"CMP",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"",        SEG_DS,     0,              0,              0},
    {"AAS",     0,          0,              0,              0},

    // 0x40
    {"INC",     0,          PARAM_EAX,      0,              0},
    {"INC",     0,          PARAM_ECX,      0,              0},
    {"INC",     0,          PARAM_EDX,      0,              0},
    {"INC",     0,          PARAM_EBX,      0,              0},
    {"INC",     0,          PARAM_ESP,      0,              0},
    {"INC",     0,          PARAM_EBP,      0,              0},
    {"INC",     0,          PARAM_ESI,      0,              0},
    {"INC",     0,          PARAM_EDI,      0,              0},
    {"DEC",     0,          PARAM_EAX,      0,              0},
    {"DEC",     0,          PARAM_ECX,      0,              0},
    {"DEC",     0,          PARAM_EDX,      0,              0},
    {"DEC",     0,          PARAM_EBX,      0,              0},
    {"DEC",     0,          PARAM_ESP,      0,              0},
    {"DEC",     0,          PARAM_EBP,      0,              0},
    {"DEC",     0,          PARAM_ESI,      0,              0},
    {"DEC",     0,          PARAM_EDI,      0,              0},

    // 0x50
    {"PUSH",    0,          PARAM_EAX,      0,              0},
    {"PUSH",    0,          PARAM_ECX,      0,              0},
    {"PUSH",    0,          PARAM_EDX,      0,              0},
    {"PUSH",    0,          PARAM_EBX,      0,              0},
    {"PUSH",    0,          PARAM_ESP,      0,              0},
    {"PUSH",    0,          PARAM_EBP,      0,              0},
    {"PUSH",    0,          PARAM_ESI,      0,              0},
    {"PUSH",    0,          PARAM_EDI,      0,              0},
    {"POP",     0,          PARAM_EAX,      0,              0},
    {"POP",     0,          PARAM_ECX,      0,              0},
    {"POP",     0,          PARAM_EDX,      0,              0},
    {"POP",     0,          PARAM_EBX,      0,              0},
    {"POP",     0,          PARAM_ESP,      0,              0},
    {"POP",     0,          PARAM_EBP,      0,              0},
    {"POP",     0,          PARAM_ESI,      0,              0},
    {"POP",     0,          PARAM_EDI,      0,              0},

    // 0x60
    {"PUSHA",   0,          0,              0,              0},
    {"POPA",    0,          0,              0,              0},
    {"BOUND",   MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"ARPL",    MODRM,      PARAM_RM,       PARAM_REG16,    0},
    {"",        SEG_FS,     0,              0,              0},
    {"",        SEG_GS,     0,              0,              0},
    {"",        OP_SIZE,    0,              0,              0},
    {"",        ADDR_SIZE,  0,              0,              0},
    {"PUSH",    0,          PARAM_IMM,      0,              0},
    {"IMUL",    MODRM,      PARAM_REG,      PARAM_RM,       PARAM_IMM},
    {"PUSH",    0,          PARAM_I8,       0,              0},
    {"IMUL",    MODRM,      PARAM_REG,      PARAM_RM,       PARAM_I8},
    {"INSB",    0,          0,              0,              0},
    {"INSW\0INSD", VAR_NAME, 0,             0,              0},
    {"OUTSB",   0,          PARAM_SEGOVER,  0,              0},
    {"OUTSW\0OUTSD", VAR_NAME, PARAM_SEGOVER, 0,            0},

    // 0x70
    {"JO",      0,          PARAM_REL8,     0,              0},
    {"JNO",     0,          PARAM_REL8,     0,              0},
    {"JB",      0,          PARAM_REL8,     0,              0},
    {"JAE",     0,          PARAM_REL8,     0,              0},
    {"JE",      0,          PARAM_REL8,     0,              0},
    {"JNE",     0,          PARAM_REL8,     0,              0},
    {"JBE",     0,          PARAM_REL8,     0,              0},
    {"JA",      0,          PARAM_REL8,     0,              0},
    {"JS",      0,          PARAM_REL8,     0,              0},
    {"JNS",     0,          PARAM_REL8,     0,              0},
    {"JP",      0,          PARAM_REL8,     0,              0},
    {"JNP",     0,          PARAM_REL8,     0,              0},
    {"JL",      0,          PARAM_REL8,     0,              0},
    {"JGE",     0,          PARAM_REL8,     0,              0},
    {"JLE",     0,          PARAM_REL8,     0,              0},
    {"JG",      0,          PARAM_REL8,     0,              0},

    // 0x80
    {"",        GROUP80,    0,              0,              0},
    {"",        GROUP81,    0,              0,              0},
    {"",        GROUP80,    0,              0,              0},
    {"",        GROUP83,    0,              0,              0},
    {"TEST",    MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"TEST",    MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"XCHG",    MODRM,      PARAM_REG8,     PARAM_RM8,      0},
    {"XCHG",    MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"MOV",     MODRM,      PARAM_RM8,      PARAM_REG8,     0},
    {"MOV",     MODRM,      PARAM_RM,       PARAM_REG,      0},
    {"MOV",     MODRM,      PARAM_REG8,     PARAM_RM8,      0},
    {"MOV",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"MOV",     MODRM,      PARAM_RM16,     PARAM_SREG,     0},
    {"LEA",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"MOV",     MODRM,      PARAM_SREG,     PARAM_RM16,     0},
    {"POP",     MODRM,      PARAM_RM,       0,              0},

    // 0x90
    {"NOP",     0,          0,              0,              0},
    {"XCHG",    0,          PARAM_EAX,      PARAM_ECX,      0},     
    {"XCHG",    0,          PARAM_EAX,      PARAM_EDX,      0},
    {"XCHG",    0,          PARAM_EAX,      PARAM_EBX,      0},
    {"XCHG",    0,          PARAM_EAX,      PARAM_ESP,      0},
    {"XCHG",    0,          PARAM_EAX,      PARAM_EBP,      0},
    {"XCHG",    0,          PARAM_EAX,      PARAM_ESI,      0},
    {"XCHG",    0,          PARAM_EAX,      PARAM_EDI,      0},
    {"CBW\0CWDE",VAR_NAME,  0,              0,              0},
    {"CWD\0CDQ",VAR_NAME,   0,              0,              0},
    {"CALL",    0,          PARAM_ADDR,     0,              0},
    {"WAIT",    0,          0,              0,              0},
    {"PUSHF",   0,          0,              0,              0},
    {"POPF",    0,          0,              0,              0},
    {"SAHF",    0,          0,              0,              0},
    {"LAHF",    0,          0,              0,              0},

    // 0xA0
    {"MOV",     0,          PARAM_AL,       PARAM_OFFSET,   0},
    {"MOV",     0,          PARAM_EAX,      PARAM_OFFSET,   0},
    {"MOV",     0,          PARAM_OFFSET,   PARAM_AL,       0},
    {"MOV",     0,          PARAM_OFFSET,   PARAM_EAX,      0},
    {"MOVSB",   0,          PARAM_SEGOVER,  0,              0},
    {"MOVSW\0MOVSD",VAR_NAME,PARAM_SEGOVER, 0,              0},
    {"CMPSB",   0,          PARAM_SEGOVER,  0,              0},
    {"CMPSW\0CMPSD",VAR_NAME,PARAM_SEGOVER, 0,              0},
    {"TEST",    0,          PARAM_AL,       PARAM_UI8,      0},
    {"TEST",    0,          PARAM_EAX,      PARAM_IMM,      0},
    {"STOSB",   0,          0,              0,              0},
    {"STOSW\0STOSD",VAR_NAME,0,             0,              0},
    {"LODSB",   0,          PARAM_SEGOVER,  0,              0},
    {"LODSW\0LODSD",VAR_NAME,PARAM_SEGOVER, 0,              0},
    {"SCASB",   0,          PARAM_SEGOVER,  0,              0},
    {"SCASW\0SCASD",VAR_NAME,0,             0,              0},

    // 0xB0
    {"MOV",     0,          PARAM_AL,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_CL,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_DL,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_BL,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_AH,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_CH,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_DH,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_BH,       PARAM_UI8,      0},
    {"MOV",     0,          PARAM_EAX,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_ECX,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_EDX,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_EBX,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_ESP,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_EBP,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_ESI,      PARAM_IMM,      0},
    {"MOV",     0,          PARAM_EDI,      PARAM_IMM,      0},

    // 0xC0
    {"",        GROUPC0,    0,              0,              0},
    {"",        GROUPC1,    0,              0,              0},
    {"RET",     0,          PARAM_UI16,     0,              0},
    {"RET",     0,          0,              0,              0},
    {"LES",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"LDS",     MODRM,      PARAM_REG,      PARAM_RM,       0},
    {"MOV",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"MOV",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"ENTER",   0,          PARAM_UI16,     PARAM_UI8,      0},
    {"LEAVE",   0,          0,              0,              0},
    {"RETF",    0,          PARAM_UI16,     0,              0},
    {"RETF",    0,          0,              0,              0},
    {"INT 3",   0,          0,              0,              0},
    {"INT",     0,          PARAM_UI8,      0,              0},
    {"INTO",    0,          0,              0,              0},
    {"IRET",    0,          0,              0,              0},

    // 0xD0
    {"",        GROUPD0,    0,              0,              0},
    {"",        GROUPD1,    0,              0,              0},
    {"",        GROUPD2,    0,              0,              0},
    {"",        GROUPD3,    0,              0,              0},
    {"AAM",     0,          PARAM_UI8,      0,              0},
    {"AAD",     0,          PARAM_UI8,      0,              0},
    {"SALC",    0,          0,              0,              0},
    {"XLAT",    0,          0,              0,              0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},

    // 0xE0
    {"LOOPNE",  0,          PARAM_REL8,     0,              0},
    {"LOOPE",   0,          PARAM_REL8,     0,              0},
    {"LOOP",    0,          PARAM_REL8,     0,              0},
    {"JCXZ",    0,          PARAM_REL8,     0,              0},
    {"IN",      0,          PARAM_AL,       PARAM_UI8,      0},
    {"IN",      0,          PARAM_EAX,      PARAM_UI8,      0},
    {"OUT",     0,          PARAM_UI8,      PARAM_AL,       0},
    {"OUT",     0,          PARAM_UI8,      PARAM_EAX,      0},
    {"CALL",    0,          PARAM_REL,      0,              0},
    {"JMP",     0,          PARAM_REL,      0,              0},
    {"JMP",     0,          PARAM_ADDR,     0,              0},
    {"JMP",     0,          PARAM_REL8,     0,              0},
    {"IN",      0,          PARAM_AL,       PARAM_DX,       0},
    {"IN",      0,          PARAM_EAX,      PARAM_DX,       0},
    {"OUT",     0,          PARAM_DX,       PARAM_AL,       0},
    {"OUT",     0,          PARAM_DX,       PARAM_EAX,      0},

    // 0xF0
    {"LOCK",    PREFIX,     0,              0,              0},
    {0},
    {"REPNE",   PREFIX,     0,              0,              0},
    {"REPE",    PREFIX,     0,              0,              0},
    {"HLT",     0,          0,              0,              0},
    {"CMC",     0,          0,              0,              0},
    {"",        GROUPF6,    0,              0,              0},
    {"",        GROUPF7,    0,              0,              0},
    {"CLC",     0,          0,              0,              0},
    {"STC",     0,          0,              0,              0},
    {"CLI",     0,          0,              0,              0},
    {"STI",     0,          0,              0,              0},
    {"CLD",     0,          0,              0,              0},
    {"STD",     0,          0,              0,              0},
    {"",        GROUPFE,    0,              0,              0},
    {"",        GROUPFF,    0,              0,              0}
};

i386_instruction_t opcode_table_2[256] = {
	// 0x00
	{"",        GROUP0F00,  0,              0,              0},
	{"",        GROUP0F01,  0,              0,              0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x10
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x20
	{"MOV",     MODRM,      PARAM_RM32,     PARAM_CREG,     0},
	{"MOV",     MODRM,      PARAM_RM32,     PARAM_DREG,     0},
	{"MOV",     MODRM,      PARAM_CREG,     PARAM_RM32,     0},
	{"MOV",     MODRM,      PARAM_DREG,     PARAM_RM32,     0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x30
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x40
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x50
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x60
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x70
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0x80
    {"JO",      0,          PARAM_REL,      0,              0},
    {"JNO",     0,          PARAM_REL,      0,              0},
    {"JB",      0,          PARAM_REL,      0,              0},
    {"JAE",     0,          PARAM_REL,      0,              0},
    {"JE",      0,          PARAM_REL,      0,              0},
    {"JNE",     0,          PARAM_REL,      0,              0},
    {"JBE",     0,          PARAM_REL,      0,              0},
    {"JA",      0,          PARAM_REL,      0,              0},
    {"JS",      0,          PARAM_REL,      0,              0},
    {"JNS",     0,          PARAM_REL,      0,              0},
    {"JP",      0,          PARAM_REL,      0,              0},
    {"JNP",     0,          PARAM_REL,      0,              0},
    {"JL",      0,          PARAM_REL,      0,              0},
    {"JGE",     0,          PARAM_REL,      0,              0},
    {"JLE",     0,          PARAM_REL,      0,              0},
    {"JG",      0,          PARAM_REL,      0,              0},

	// 0x90
    {"SETO",    MODRM,      PARAM_RM8,      0,              0},
    {"SETNO",   MODRM,      PARAM_RM8,      0,              0},
    {"SETB",    MODRM,      PARAM_RM8,      0,              0},
    {"SETAE",   MODRM,      PARAM_RM8,      0,              0},
    {"SETE",    MODRM,      PARAM_RM8,      0,              0},
    {"SETNE",   MODRM,      PARAM_RM8,      0,              0},
    {"SETBE",   MODRM,      PARAM_RM8,      0,              0},
    {"SETA",    MODRM,      PARAM_RM8,      0,              0},
    {"SETS",    MODRM,      PARAM_RM8,      0,              0},
    {"SETNS",   MODRM,      PARAM_RM8,      0,              0},
    {"SETP",    MODRM,      PARAM_RM8,      0,              0},
    {"SETNP",   MODRM,      PARAM_RM8,      0,              0},
    {"SETL",    MODRM,      PARAM_RM8,      0,              0},
    {"SETGE",   MODRM,      PARAM_RM8,      0,              0},
    {"SETLE",   MODRM,      PARAM_RM8,      0,              0},
    {"SETG",    MODRM,      PARAM_RM8,      0,              0},

	// 0xa0
	{"PUSH FS", 0,          0,              0,              0},
	{"POP FS",  0,          0,              0,              0},
	{"CPUID",   0,          0,              0,              0},
	{"BT",      MODRM,      PARAM_RM,       PARAM_REG,      0},
	{"SHLD",    MODRM,      PARAM_RM,       PARAM_REG,      PARAM_UI8},
	{"SHLD",    MODRM,      PARAM_RM,       PARAM_REG,      PARAM_CL},
	{0},
	{0},
	{"POP GS",  0,          0,              0,              0},
	{"POP FS",  0,          0,              0,              0},
	{"RSM",     0,          0,              0,              0},
	{"BTS",     MODRM,      PARAM_RM,       PARAM_REG,      0},
	{"SHRD",    MODRM,      PARAM_RM,       PARAM_REG,      PARAM_UI8},
	{"SHRD",    MODRM,      PARAM_RM,       PARAM_REG,      PARAM_CL},
	{0},
	{"IMUL",    MODRM,      PARAM_REG,      PARAM_RM,       0},

	// 0xb0
	{"CMPXCHG", MODRM,      PARAM_RM8,      PARAM_REG8,     0},
	{"CMPXCHG", MODRM,      PARAM_RM,       PARAM_REG,      0},
	{"LSS",     MODRM,      PARAM_REG,      PARAM_RM,       0},
	{"BTR",     MODRM,      PARAM_RM,       PARAM_REG,      0},
	{"LFS",     MODRM,      PARAM_REG,      PARAM_RM,       0},
	{"LGS",     MODRM,      PARAM_REG,      PARAM_RM,       0},
	{"MOVZX",   MODRM,      PARAM_REG,      PARAM_RM8,      0},
	{"MOVZX",   MODRM,      PARAM_REG,      PARAM_RM16,     0},
	{0},
	{0},
	{0},
	{"BTC",     MODRM,      PARAM_RM,       PARAM_REG,      0},
	{"BSF",     MODRM,      PARAM_REG,      PARAM_RM,       0},
	{"BSR",     MODRM,      PARAM_REG,      PARAM_RM,       0},
	{"MOVSX",   MODRM,      PARAM_REG,      PARAM_RM8,      0},
	{"MOVSX",   MODRM,      PARAM_REG,      PARAM_RM8,      0},

	// 0xc0
	{"XADD",    MODRM,      PARAM_REG,      PARAM_RM,       0},
	{"XADD",    MODRM,      PARAM_RM,       PARAM_REG,      0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{"BSWAP",   0,          PARAM_EAX,      0,              0},
	{"BSWAP",   0,          PARAM_ECX,      0,              0},
	{"BSWAP",   0,          PARAM_EDX,      0,              0},
	{"BSWAP",   0,          PARAM_EBX,      0,              0},
	{"BSWAP",   0,          PARAM_ESP,      0,              0},
	{"BSWAP",   0,          PARAM_EBP,      0,              0},
	{"BSWAP",   0,          PARAM_ESI,      0,              0},
	{"BSWAP",   0,          PARAM_EDI,      0,              0},

	// 0xd0
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0xe0
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},

	// 0xf0
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0},
	{0}
};

i386_instruction_t opcode_table_group80[8] = {
    {"ADD",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"OR",      MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"ADC",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"SBB",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"AND",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"SUB",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"XOR",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"CMP",     MODRM,      PARAM_RM8,      PARAM_UI8,      0}
};

i386_instruction_t opcode_table_group81[8] = {
    {"ADD",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"OR",      MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"ADC",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"SBB",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"AND",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"SUB",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"XOR",     MODRM,      PARAM_RM,       PARAM_IMM,      0},
    {"CMP",     MODRM,      PARAM_RM,       PARAM_IMM,      0}
};

i386_instruction_t opcode_table_group83[8] = {
    {"ADD",     MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"OR",      MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"ADC",     MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"SBB",     MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"AND",     MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"SUB",     MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"XOR",     MODRM,      PARAM_RM,       PARAM_I8,       0},
    {"CMP",     MODRM,      PARAM_RM,       PARAM_I8,       0}
};

i386_instruction_t opcode_table_groupC0[8] = {
    {"ROL",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"ROR",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"RCL",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"RCR",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"SHL",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"SHR",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"SAL",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
    {"SAR",     MODRM,      PARAM_RM8,      PARAM_UI8,      0},
};

i386_instruction_t opcode_table_groupC1[8] = {
    {"ROL",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"ROR",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"RCL",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"RCR",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"SHL",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"SHR",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"SAL",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
    {"SAR",     MODRM,      PARAM_RM,       PARAM_UI8,      0},
};

i386_instruction_t opcode_table_groupD0[8] = {
    {"ROL",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"ROR",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"RCL",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"RCR",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"SHL",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"SHR",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"SAL",     MODRM,      PARAM_RM8,      PARAM_1,        0},
    {"SAR",     MODRM,      PARAM_RM8,      PARAM_1,        0},
};

i386_instruction_t opcode_table_groupD1[8] = {
    {"ROL",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"ROR",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"RCL",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"RCR",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"SHL",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"SHR",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"SAL",     MODRM,      PARAM_RM,       PARAM_1,        0},
    {"SAR",     MODRM,      PARAM_RM,       PARAM_1,        0},
};

i386_instruction_t opcode_table_groupD2[8] = {
    {"ROL",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"ROR",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"RCL",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"RCR",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"SHL",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"SHR",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"SAL",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
    {"SAR",     MODRM,      PARAM_RM8,      PARAM_CL,       0},
};

i386_instruction_t opcode_table_groupD3[8] = {
    {"ROL",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"ROR",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"RCL",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"RCR",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"SHL",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"SHR",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"SAL",     MODRM,      PARAM_RM,       PARAM_CL,       0},
    {"SAR",     MODRM,      PARAM_RM,       PARAM_CL,       0},
};

i386_instruction_t opcode_table_groupF6[8] = {
    {"TEST",    0,          PARAM_RM8,      PARAM_UI8,      0},
    {"TEST",    0,          PARAM_RM8,      PARAM_UI8,      0},
    {"NOT",     0,          PARAM_RM8,      0,              0},
    {"NEG",     0,          PARAM_RM8,      0,              0},
    {"MUL",     0,          PARAM_RM8,      0,              0},
    {"IMUL",    0,          PARAM_RM8,      0,              0},
    {"DIV",     0,          PARAM_RM8,      0,              0},
    {"IDIV",    0,          PARAM_RM8,      0,              0},
};

i386_instruction_t opcode_table_groupF7[8] = {
    {"TEST",    0,          PARAM_RM,       PARAM_IMM,      0},
    {"TEST",    0,          PARAM_RM,       PARAM_IMM,      0},
    {"NOT",     0,          PARAM_RM,       0,              0},
    {"NEG",     0,          PARAM_RM,       0,              0},
    {"MUL",     0,          PARAM_RM,       0,              0},
    {"IMUL",    0,          PARAM_RM,       0,              0},
    {"DIV",     0,          PARAM_RM,       0,              0},
    {"IDIV",    0,          PARAM_RM,       0,              0},
};

i386_instruction_t opcode_table_groupFE[8] = {
    {"INC",     0,          PARAM_RM8,      0,              0},
    {"DEC",     0,          PARAM_RM8,      0,              0},
};

i386_instruction_t opcode_table_groupFF[8] = {
    {"INC",     0,          PARAM_RM,       0,              0},
    {"DEC",     0,          PARAM_RM,       0,              0},
    {"CALL",    0,          PARAM_RM,       0,              0},
    {"CALL FAR",0,          PARAM_RM,       0,              0},
    {"JMP",     0,          PARAM_RM,       0,              0},
    {"JMP FAR", 0,          PARAM_RM,       0,              0},
    {"PUSH",    0,          PARAM_RM,       0,              0},
};

i386_instruction_t opcode_table_group0F00[8] = {
    {"SLDT",    0,          PARAM_RM,       0,              0},
    {"STR",     0,          PARAM_RM,       0,              0},
    {"LLDT",    0,          PARAM_RM,       0,              0},
    {"LTR",     0,          PARAM_RM,       0,              0},
    {"VERR",    0,          PARAM_RM,       0,              0},
    {"VERW",    0,          PARAM_RM,       0,              0},
};

i386_instruction_t opcode_table_group0F01[8] = {
    {"SGDT",    0,          PARAM_RM,       0,              0},
    {"SIGT",    0,          PARAM_RM,       0,              0},
    {"LGDT",    0,          PARAM_RM,       0,              0},
    {"LIDT",    0,          PARAM_RM,       0,              0},
    {"SMSW",    0,          PARAM_RM,       0,              0},
    {"???",     0,          PARAM_RM,       0,              0},
    {"LMSW",    0,          PARAM_RM,       0,              0},
    {"INVLPG" , 0,          PARAM_RM,       0,              0},
};

i386_instruction_t* opcode_tables[] = {
    opcode_table_group80, 
    opcode_table_group81, 
    opcode_table_group83, 
    opcode_table_groupC0,
    opcode_table_groupC1, 
    opcode_table_groupD0, 
    opcode_table_groupD1, 
    opcode_table_groupD2, 
    opcode_table_groupD3,
    opcode_table_groupF6, 
    opcode_table_groupF7, 
    opcode_table_groupFE,                                 
    opcode_table_groupFF, 
    opcode_table_group0F00, 
    opcode_table_group0F01,
};

